flowchart LR
 subgraph Internal["Internal Data"]
        Salesforce["Salesforce"]
        Pega["Pega"]
        ot["Other"]
        DST["DST"]
        Workday["Workday"]
        HealthEdge["HealthEdge"]
        Icertis["Icertis"]
        JobAids["Job Aids"]
  end
 subgraph External["External Data"]
        CVS["CVS Caremark"]
        EyeMed["Eye Med"]
        InterSystems["InterSystems"]
        Labcorp["Labcorp"]
        eMedNY["eMedNY"]
        Quest["Quest Diagnostics"]
        DentaQuest["DentaQuest"]
  end
 subgraph Sources["Data Sources"]
    direction TB
        Internal
        External
  end
 subgraph IngestionLayer["IngestionLayer"]
    direction TB
        SourceConnectors["Source Connectors"]
        DataContracts["Data Contracts"]
  end
 subgraph Ingestion["Data Ingestion"]
        IngestionLayer
        DataLakeHouse["Data Lakehouse Landing"]
  end
 subgraph ETL_Process["ETL_Process"]
    direction LR
        Extract["Extract"]
        Raw["Raw"]
        Transform["Transform"]
        Load["Load"]
        DataLakehouse["Data Lakehouse"]
  end
  subgraph Consumption
    Athena
    Redshift -.-> API[Data API]
  end
    DataContracts --> SourceConnectors
    IngestionLayer --> DataLakeHouse
    Sources <--> Ingestion
    Raw --> Extract
    Extract --> Transform
    Transform --> Load
    Load --> DataLakehouse
    DataLakeHouse --> Raw
    DataLakehouse --> Consumption


